#!/usr/bin/env python
"""Build a full, independently-deployable guides tree for a second brand
(AllyFind) without ever writing into this repo's own working tree, which
stays exactly what fashionhotspot.site deploys.

    python tools/build_brand.py --out <scratch dir> --brand AllyFind --site https://allyfind.com

What it does, in order:
  1. Runs tools/build.py with GUIDES_SITE/GUIDES_BRAND/GUIDES_OUT pointed at
     the scratch dir — every guide, every language's posts.html and language
     home, plus sitemap.xml.
  2. Renders brand-swapped terms.html, robots.txt and manifest.webmanifest
     from this repo's own fashionhotspot versions (structure/legal text kept
     identical, only the brand string swapped).
  3. Copies images/ and the two icon PNGs, which are brand-neutral.
  4. Downloads the handful of pages this repo does NOT own (index.html,
     about.html, contact.html, privacy.html, fh-theme.js, fh.css, deals.json
     — generated by whatsapp-deals-bot's build-static.js, already deployed
     and verified live) from --site into the scratch dir too, but ONLY so
     the link-integrity checker has real files to resolve nav/footer links
     against. They are written to <out>/_reference/ and are NEVER part of
     what this repo's own deploy step uploads — see deploy_brand.sh's
     ownership list, which matches deploy.sh's existing split exactly.
  5. Runs check_site_output.py --dir over the assembled tree. Non-zero exit
     (and no deploy) if anything required is missing or any same-origin
     link is broken.
"""
import argparse, json, re, shutil, subprocess, sys, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Files owned by the OTHER repo's build (whatsapp-deals-bot/build-static.js).
# Fetched for link-check ground truth only, never uploaded by this script.
REFERENCE_ONLY = ["index.html", "about.html", "contact.html", "privacy.html",
                  "fh-theme.js", "fh.css", "deals.json"]


def run_build_py(out_dir, site, brand):
    env = {"GUIDES_SITE": site, "GUIDES_BRAND": brand, "GUIDES_OUT": str(out_dir)}
    import os
    full_env = {**os.environ, **env}
    print(f"-- tools/build.py (SITE={site} BRAND={brand} OUT={out_dir}) --")
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "build.py")],
                        cwd=ROOT, env=full_env, capture_output=True, text=True)
    print(r.stdout)
    if r.returncode != 0:
        print(r.stderr, file=sys.stderr)
        sys.exit("tools/build.py failed")


def render_terms(out_dir, brand):
    src = (ROOT / "terms.html").read_text(encoding="utf-8")
    # The only brand-specific spots in this file are the literal lowercase
    # "fashionhotspot" wordmark (title, one body sentence, the footer). The
    # legal text itself and the contact@ address are brand-independent and
    # already correct for both domains (see HANDOVER.md's contact-email note).
    out = src.replace("fashionhotspot", brand)
    (out_dir / "terms.html").write_text(out, encoding="utf-8")


def render_robots(out_dir, site):
    (out_dir / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {site}/sitemap.xml\n", encoding="utf-8")


def render_manifest(out_dir, brand):
    src = json.loads((ROOT / "manifest.webmanifest").read_text(encoding="utf-8"))
    src["name"] = f"{brand} — Deals & Coupons"
    src["short_name"] = brand
    (out_dir / "manifest.webmanifest").write_text(
        json.dumps(src, indent=2), encoding="utf-8")


def copy_assets(out_dir):
    for name in ("icon-192.png", "icon-512.png"):
        shutil.copy2(ROOT / name, out_dir / name)
    dst_images = out_dir / "images"
    if dst_images.exists():
        shutil.rmtree(dst_images)
    shutil.copytree(ROOT / "images", dst_images)


def fetch_reference(out_dir, site):
    ref_dir = out_dir / "_reference"
    ref_dir.mkdir(exist_ok=True)
    ok, failed = [], []
    for name in REFERENCE_ONLY:
        url = site.rstrip("/") + "/" + name
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "allyfind-build/1.0"})
            with urllib.request.urlopen(req, timeout=20) as r:
                data = r.read()
            (ref_dir / name).write_bytes(data)
            # Also drop a copy at the tree root (not uploaded — deploy_brand.sh
            # excludes REFERENCE_ONLY explicitly) purely so the link checker,
            # which resolves paths against the tree root, can find them.
            (out_dir / name).write_bytes(data)
            ok.append(name)
        except Exception as e:
            failed.append((name, str(e)))
    print(f"-- reference files fetched from {site}: {len(ok)}/{len(REFERENCE_ONLY)} ok --")
    if failed:
        for n, e in failed:
            print(f"   ! {n}: {e}")
        sys.exit("could not fetch reference files needed for link checking — is the site up?")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--brand", default="AllyFind")
    ap.add_argument("--site", default="https://allyfind.com")
    args = ap.parse_args()

    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_build_py(out_dir, args.site, args.brand)
    render_terms(out_dir, args.brand)
    render_robots(out_dir, args.site)
    render_manifest(out_dir, args.brand)
    copy_assets(out_dir)
    fetch_reference(out_dir, args.site)

    print(f"\nBuild assembled at {out_dir}")
    print("Now run: python tools/check_site_output.py --dir "
          f'"{out_dir}" --site {args.site} --brand {args.brand}')


if __name__ == "__main__":
    main()
