#!/bin/bash
# Publish a build_brand.py output tree to its own FTP target.
#
# Built for AllyFind but generic: this never touches fashionhotspot.site or
# its .env.ftp / deploy.sh — it takes a completely separate source tree and a
# completely separate FTP credentials file, so it cannot collide with the
# existing site's deploy path no matter when it runs.
#
# Reuses deploy.sh's hard-won upload pattern (chunked curl, one login per
# chunk instead of per file — see deploy.sh's own comments for the 2026-09-08
# Hostinger anti-abuse block this avoids) rather than reinventing it.
#
#   ./tools/deploy_brand.sh <src-dir> <env-file> [--dry-run] [--force]
set -euo pipefail

SRC_DIR="${1:?usage: deploy_brand.sh <src-dir> <env-file> [--dry-run] [--force]}"
ENV_FILE="${2:?usage: deploy_brand.sh <src-dir> <env-file> [--dry-run] [--force]}"
shift 2
DRY_RUN=0; FORCE=0
for a in "$@"; do
  [ "$a" = "--dry-run" ] && DRY_RUN=1
  [ "$a" = "--force" ] && FORCE=1
done

[ -d "$SRC_DIR" ] || { echo "missing source dir: $SRC_DIR"; exit 1; }
[ -f "$ENV_FILE" ] || { echo "missing env file: $ENV_FILE"; exit 1; }
# shellcheck disable=SC1090
source "$ENV_FILE"
if [ -z "${FTP_PASS:-}" ]; then
  echo "FTP_PASS not set in $ENV_FILE"; exit 1
fi
FTP_PATH="${FTP_PATH:-}"

cd "$SRC_DIR"
# _reference/ AND the same filenames duplicated at the tree root are link-check
# ground truth for pages this repo does NOT own (index.html, about.html,
# contact.html, privacy.html, fh-theme.js, fh.css, deals.json — generated by
# whatsapp-deals-bot/build-static.js, already deployed and verified live).
# build_brand.py writes them so the link checker can resolve nav/footer links
# into them; deploy_brand.sh must never re-upload them, or a stale fetch could
# overwrite the other repo's live build with an older snapshot.
OWNED_ELSEWHERE_RE='^(index\.html|about\.html|contact\.html|privacy\.html|fh-theme\.js|fh\.css|deals\.json)$'
mapfile -t FILES < <(
  find . -type f -not -path './_reference/*' \
  | sed 's|^\./||' \
  | grep -Ev "$OWNED_ELSEWHERE_RE" \
  | sort
)

echo "Deploying ${#FILES[@]} files from $SRC_DIR to ${FTP_HOST}${FTP_PATH:+/$FTP_PATH}"
if [ "$DRY_RUN" = 1 ]; then
  printf '   %s\n' "${FILES[@]}"
  echo "(dry run - nothing uploaded)"
  exit 0
fi

MANIFEST="$SRC_DIR/.deploy-manifest"
touch "$MANIFEST"
CHANGED=()
SKIPPED=0
for f in "${FILES[@]}"; do
  h=$(sha256sum "$f" | cut -d' ' -f1)
  if [ "$FORCE" = 0 ] && grep -qxF "$h  $f" "$MANIFEST"; then
    SKIPPED=$((SKIPPED + 1))
  else
    CHANGED+=("$f")
  fi
done

if [ "${#CHANGED[@]}" -eq 0 ]; then
  echo "Nothing to upload - all ${#FILES[@]} files match .deploy-manifest"
  exit 0
fi
echo "   $SKIPPED unchanged, ${#CHANGED[@]} to upload"

CHUNK=40
fail=0
uploaded=()
total=${#CHANGED[@]}
for ((i = 0; i < total; i += CHUNK)); do
  args=()
  batch=("${CHANGED[@]:i:CHUNK}")
  for rel in "${batch[@]}"; do
    args+=(-T "./$rel" "ftp://$FTP_HOST/${FTP_PATH:+$FTP_PATH/}$rel")
  done
  n=$((i + ${#batch[@]}))
  printf '   uploading %d-%d of %d ... ' "$((i + 1))" "$n" "$total"
  if curl -sS --fail --ftp-create-dirs -u "$FTP_USER:$FTP_PASS" "${args[@]}" >/dev/null 2>&1; then
    echo "ok"
    uploaded+=("${batch[@]}")
  else
    echo "FAILED"
    fail=$((fail + ${#batch[@]}))
  fi
done

if [ "${#uploaded[@]}" -gt 0 ]; then
  tmp=$(mktemp)
  cp "$MANIFEST" "$tmp"
  for rel in "${uploaded[@]}"; do
    grep -v "  $rel\$" "$tmp" > "$tmp.n" 2>/dev/null || true
    mv "$tmp.n" "$tmp"
    printf '%s  %s\n' "$(sha256sum "./$rel" | cut -d' ' -f1)" "$rel" >> "$tmp"
  done
  sort -k2 "$tmp" > "$MANIFEST"
  rm -f "$tmp"
fi

echo
if [ "$fail" -gt 0 ]; then
  echo "Deploy finished with $fail file(s) unsent out of $total"
  exit 1
fi
echo "Deploy complete - $total uploaded, $SKIPPED unchanged"
