<?php
/**
 * Adult and offensive term blocklist for api/search.php.
 *
 * GENERATED - do not hand-edit. Rebuild with the script in the repo notes.
 *
 * Source: LDNOOBW 'List of Dirty, Naughty, Obscene and Otherwise Bad Words',
 * the list most moderation tooling starts from, across en, es, fr, de, ru, ar, it, pt.
 * Hebrew is added by hand because the published list has one entry and this
 * is an Israeli site.
 *
 * MATCHING IS WHOLE-WORD, and ALLOW is checked first. Both matter:
 * substring matching would block 'analysis' for containing a slur and
 * 'grape' for containing another - the Scunthorpe problem - and without the
 * allowlist a breast pump, a cocktail shaker and a massage gun would all be
 * refused. Every ALLOW entry is a real product someone would search for.
 */

return [
    'block' => [
        "2 girls 1 cup",
        "2g1c",
        "aborto",
        "acrotomophilia",
        "alabama hot pocket",
        "alaskan pipeline",
        "allupato",
        "amador",
        "ammucchiata",
        "anal",
        "anale",
        "analritter",
        "anilingus",
        "anus",
        "apeshit",
        "aranha",
        "ariano",
        "arrapato",
        "arrusa",
        "arruso",
        "arsch",
        "arschficker",
        "arschlecker",
        "arschloch",
        "arsehole",
        "asesinato",
        "asno",
        "ass",
        "assatanato",
        "asshole",
        "assmunch",
        "auto erotic",
        "autoerotic",
        "babeland",
        "baby batter",
        "baby juice",
        "bagascia",
        "bagassa",
        "bagnarsi",
        "baiser",
        "balalao",
        "baldracca",
        "ball gag",
        "ball gravy",
        "ball kicking",
        "ball licking",
        "ball sack",
        "ball sucking",
        "balle",
        "bander",
        "bangbros",
        "bangbus",
        "bareback",
        "barely legal",
        "barenaked",
        "bastard",
        "bastardo",
        "bastinado",
        "battere",
        "battona",
        "bbw",
        "bdsm",
        "beaner",
        "beaners",
        "beastiality",
        "beaver cleaver",
        "beaver lips",
        "belino",
        "bestiality",
        "bicha",
        "big black",
        "big breasts",
        "big knockers",
        "big tits",
        "biga",
        "bigornette",
        "bimbo",
        "bimbos",
        "birdlock",
        "biscate",
        "bissexual",
        "bitch",
        "bitches",
        "bite",
        "bitte",
        "black cock",
        "bloblos",
        "blonde action",
        "blonde on blonde action",
        "blow job",
        "blow your load",
        "blowjob",
        "blue waffle",
        "blumpkin",
        "bocchinara",
        "bocchino",
        "boceta",
        "bofilo",
        "boiata",
        "bollera",
        "bollocks",
        "bondage",
        "boner",
        "bonze",
        "boob",
        "boobs",
        "booty call",
        "bordel",
        "bordello",
        "bosta",
        "bourré",
        "bourrée",
        "brackmard",
        "branlage",
        "branler",
        "branlette",
        "branleur",
        "branleuse",
        "bratze",
        "braulio de borracha",
        "brinca",
        "brouter le cresson",
        "brown showers",
        "brunette action",
        "bucaiolo",
        "budiùlo",
        "bukkake",
        "bulldyke",
        "bullet vibe",
        "bullshit",
        "bumbum",
        "bumsen",
        "bung hole",
        "bunghole",
        "burro",
        "busone",
        "busty",
        "butt",
        "buttcheeks",
        "butthole",
        "bychara",
        "byk",
        "cabrao",
        "cabrón",
        "caca",
        "cacca",
        "cacete",
        "caciocappella",
        "cadavere",
        "cagar",
        "cagare",
        "cagata",
        "cagna",
        "camel toe",
        "camgirl",
        "camisinha",
        "camslut",
        "camwhore",
        "caralho",
        "carpet muncher",
        "carpetmuncher",
        "casci",
        "cazzata",
        "cazzimma",
        "cazzo",
        "cazzone",
        "cerveja",
        "cesso",
        "chatte",
        "checca",
        "chernozhopyi",
        "chiappa",
        "chiasse",
        "chiavare",
        "chiavata",
        "chier",
        "chiottes",
        "chochota",
        "chocolate rosebuds",
        "chupada",
        "chupapollas",
        "chupar",
        "chupetón",
        "cialis",
        "ciospo",
        "circlejerk",
        "ciucciami il cazzo",
        "cleveland steamer",
        "clit",
        "clito",
        "clitoris",
        "clover clamps",
        "clusterfuck",
        "cocaína",
        "cock",
        "cocks",
        "coglione",
        "coglioni",
        "coito",
        "colhoes",
        "comer",
        "con",
        "cona",
        "concha",
        "concha de tu madre",
        "connard",
        "connasse",
        "conne",
        "consolo",
        "coon",
        "coons",
        "coprofagía",
        "coprolagnia",
        "coprophilia",
        "cornhole",
        "corno",
        "cornuto",
        "couilles",
        "cozza",
        "coño",
        "cramouille",
        "creampie",
        "cul",
        "culattina",
        "culattone",
        "culo",
        "cum",
        "cumming",
        "cumshot",
        "cumshots",
        "cunnilingus",
        "cunt",
        "dar o rabo",
        "darkie",
        "date rape",
        "daterape",
        "deep throat",
        "deepthroat",
        "dendrophilia",
        "dick",
        "dildo",
        "dingleberries",
        "dingleberry",
        "dirty pillows",
        "dirty sanchez",
        "ditalino",
        "dog style",
        "doggie style",
        "doggiestyle",
        "doggy style",
        "doggystyle",
        "dolboy'eb",
        "dolcett",
        "domination",
        "dominatrix",
        "dommes",
        "donkey punch",
        "double dong",
        "double penetration",
        "dp action",
        "drogas",
        "dry hump",
        "dum raio",
        "dvda",
        "déconne",
        "déconner",
        "dödel",
        "eat my ass",
        "ebalnik",
        "ebalo",
        "ebalom sch'elkat",
        "ecchi",
        "ejaculation",
        "emmerdant",
        "emmerder",
        "emmerdeur",
        "emmerdeuse",
        "enculeur",
        "enculeurs",
        "enculé",
        "enculée",
        "enfoiré",
        "enfoirée",
        "erotic",
        "erotism",
        "escort",
        "esperma",
        "esporra",
        "eunuch",
        "fag",
        "faggot",
        "fava",
        "fecal",
        "felch",
        "fellatio",
        "feltch",
        "female squirting",
        "femdom",
        "femminuccia",
        "fica",
        "fick",
        "ficken",
        "fiesta de salchichas",
        "figa",
        "figging",
        "figlio di buona donna",
        "figlio di puttana",
        "figone",
        "filho da puta",
        "fille de pute",
        "fils de pute",
        "fingerbang",
        "fingering",
        "finocchio",
        "fisting",
        "flittchen",
        "foda",
        "foda-se",
        "foder",
        "follador",
        "follar",
        "folle",
        "foot fetish",
        "footjob",
        "fottere",
        "fottersi",
        "fotze",
        "foutre",
        "fracicone",
        "frango assado",
        "fratze",
        "fregna",
        "frocio",
        "froscio",
        "frotting",
        "fuck",
        "fuck buttons",
        "fuckin",
        "fucking",
        "fucktards",
        "fudge packer",
        "fudgepacker",
        "futanari",
        "g-spot",
        "gang bang",
        "gangbang",
        "gay sex",
        "genitals",
        "gerbe",
        "gerber",
        "giant cock",
        "gilipichis",
        "gilipollas",
        "girl on",
        "girl on top",
        "girls gone wild",
        "goatcx",
        "goatse",
        "god damn",
        "gokkun",
        "gol",
        "golden shower",
        "goldone",
        "goo girl",
        "goodpoop",
        "goregasm",
        "gouine",
        "gozar",
        "grande folle",
        "grelho",
        "grogniasse",
        "grope",
        "group sex",
        "guardone",
        "gueule",
        "guro",
        "hacer una paja",
        "haciendo el amor",
        "hackfresse",
        "hand job",
        "handjob",
        "hard core",
        "hardcore",
        "hentai",
        "heroína",
        "heterosexual",
        "hija de puta",
        "hijaputa",
        "hijo de puta",
        "hijoputa",
        "homem gay",
        "homoerotic",
        "homoerótico",
        "homosexual",
        "honkey",
        "hooker",
        "horny",
        "hot carl",
        "hot chick",
        "how to kill",
        "how to murder",
        "huge fat",
        "humping",
        "hure",
        "hurensohn",
        "idiota",
        "imbecille",
        "imbécil",
        "incazzarsi",
        "incest",
        "incoglionirsi",
        "inferno",
        "infierno",
        "ingoio",
        "intercourse",
        "ische",
        "jack off",
        "jail bait",
        "jailbait",
        "jelly donut",
        "jerk off",
        "jigaboo",
        "jiggaboo",
        "jiggerboo",
        "jilipollas",
        "jizz",
        "jouir",
        "juggs",
        "kackbratze",
        "kacke",
        "kacken",
        "kackwurst",
        "kampflesbe",
        "kanake",
        "kapullo",
        "kike",
        "kimme",
        "kinbaku",
        "kinkster",
        "kinky",
        "knobbing",
        "la putain de ta mère",
        "lameculos",
        "leather restraint",
        "leather straight jacket",
        "leccaculo",
        "lecchino",
        "lemon party",
        "livesex",
        "lofare",
        "loffa",
        "loffare",
        "lolita",
        "lovemaking",
        "lésbica",
        "lümmel",
        "maciza",
        "macizorra",
        "make me come",
        "maldito",
        "male squirting",
        "malpt",
        "mama",
        "mamada",
        "mannaggia",
        "marica",
        "mariconazo",
        "maricón",
        "martillo",
        "masturbate",
        "masturbating",
        "masturbation",
        "menage a trois",
        "merda",
        "merdata",
        "merde",
        "merdeuse",
        "merdeux",
        "merdoso",
        "meuf",
        "mierda",
        "mignotta",
        "milf",
        "minchia",
        "minchione",
        "missionary position",
        "mona",
        "mong",
        "monta",
        "montare",
        "morgenlatte",
        "motherfucker",
        "mound of venus",
        "mr hands",
        "mudack",
        "muff diver",
        "muffdiving",
        "mufti",
        "muschi",
        "mussa",
        "ménage à trois",
        "möpse",
        "möse",
        "nackt",
        "nambla",
        "nave scuola",
        "nawashi",
        "nazi",
        "neger",
        "negro",
        "neonazi",
        "nerchia",
        "nig nog",
        "nigga",
        "nigger",
        "nimphomania",
        "nippel",
        "nipple",
        "nipples",
        "nique ta mère",
        "nique ta race",
        "nsfw",
        "nsfw images",
        "nude",
        "nudity",
        "nutte",
        "nutten",
        "nympho",
        "nymphomania",
        "nègre",
        "octopussy",
        "omorashi",
        "onanieren",
        "one cup two girls",
        "one guy one jar",
        "opizdenet",
        "orgasm",
        "orgasmus",
        "orgy",
        "orina",
        "osto'eblo",
        "ostokhuitel'no",
        "ot'ebis",
        "otmudohat",
        "otpizdit",
        "otsosi",
        "padlo",
        "padulo",
        "paedophile",
        "paki",
        "palle",
        "palloso",
        "palucher",
        "paneleiro",
        "panties",
        "panty",
        "passar um cheque",
        "patacca",
        "patonza",
        "pau",
        "pecorina",
        "pedik",
        "pedo",
        "pedobear",
        "pedophile",
        "pegging",
        "peidar",
        "pendejo",
        "penis",
        "perdet",
        "pervertido",
        "pesce",
        "petuh",
        "pezón",
        "phone sex",
        "picio",
        "pidar gnoinyj",
        "piece of shit",
        "pikey",
        "pimmel",
        "pimpern",
        "pincare",
        "pinche",
        "pinkeln",
        "pinnolone",
        "pinto",
        "pipi",
        "pippa",
        "pippone",
        "pipì",
        "pirla",
        "pis",
        "pisciare",
        "piscio",
        "pisello",
        "piss pig",
        "pissen",
        "pisser",
        "pissing",
        "pisspig",
        "pistolotto",
        "piz'det",
        "piz`dyulina",
        "pizd'uk",
        "pizda",
        "pizdato",
        "pizdatyi",
        "pizdetc",
        "pizdoi nakryt'sja",
        "playboy",
        "pleasure chest",
        "po khuy",
        "po'imat' na konchik",
        "po'iti posrat",
        "podi ku'evo",
        "poeben",
        "pole smoker",
        "poluchit pizdy",
        "pomiciare",
        "pompa",
        "pompino",
        "ponyplay",
        "poof",
        "poon",
        "poontang",
        "poop chute",
        "poopchute",
        "popel",
        "poppen",
        "porca",
        "porca madonna",
        "porca miseria",
        "porca puttana",
        "porco",
        "porco due",
        "porco zio",
        "porn",
        "porno",
        "pornography",
        "porra",
        "pososi moyu konfetku",
        "potta",
        "pouffiasse",
        "pousse-crotte",
        "prince albert piercing",
        "prissat",
        "proebat",
        "promudobl'adsksya pizdopro'ebina",
        "propezdoloch",
        "prosrat",
        "prostituta",
        "pthc",
        "pubes",
        "punany",
        "puppami",
        "pussy",
        "puta",
        "puta que pariu",
        "puta que te pariu",
        "putain",
        "pute",
        "puttana",
        "pédale",
        "pédé",
        "péter",
        "pênis",
        "quaglia",
        "queaf",
        "queca",
        "queef",
        "quim",
        "racista",
        "raghead",
        "raging boner",
        "ramera",
        "ramoner",
        "rape",
        "raping",
        "rapist",
        "raspeezdeyi",
        "raspizdatyi",
        "raz'yebuy",
        "raz'yoba",
        "recchione",
        "rectum",
        "regina",
        "reudig",
        "reverse cowgirl",
        "rimjob",
        "rimming",
        "rincoglionire",
        "rizzarsi",
        "rompiballe",
        "rompipalle",
        "rosette",
        "rosy palm",
        "rosy palm and her 5 sisters",
        "ruffiano",
        "rusty trombone",
        "s&m",
        "s'ebat'sya",
        "sac à foutre",
        "sac à merde",
        "sacanagem",
        "saco",
        "sadism",
        "salaud",
        "salope",
        "santorum",
        "sbattere",
        "sbattersi",
        "sborra",
        "sborrata",
        "sborrone",
        "sbrodolata",
        "scat",
        "schabracke",
        "scheisser",
        "scheiße",
        "schiesser",
        "schlampe",
        "schlong",
        "schnackeln",
        "schwanzlutscher",
        "schwuchtel",
        "scissoring",
        "scopare",
        "scopata",
        "scorreggiare",
        "sega",
        "semen",
        "sex",
        "sexcam",
        "sexo",
        "sexo oral",
        "sexual",
        "sexuality",
        "sexually",
        "sexy",
        "shalava",
        "shaved beaver",
        "shaved pussy",
        "shemale",
        "shibari",
        "shit",
        "shitblimp",
        "shitty",
        "shota",
        "shrimping",
        "skeet",
        "slanteye",
        "slinguare",
        "slinguata",
        "slut",
        "smandrappata",
        "smut",
        "snatch",
        "snowballing",
        "soccia",
        "socmel",
        "sodomize",
        "sodomy",
        "soplagaitas",
        "soplapollas",
        "sorca",
        "spagnola",
        "spastic",
        "spic",
        "splooge",
        "splooge moose",
        "spompinare",
        "spooge",
        "spread legs",
        "spunk",
        "sticchio",
        "strap on",
        "strapon",
        "strappado",
        "strip club",
        "stronza",
        "stronzata",
        "stronzo",
        "styervo",
        "style doggy",
        "succhiami",
        "succhione",
        "suce",
        "suck",
        "sucks",
        "suicide girls",
        "sukin syn",
        "sultry women",
        "sveltina",
        "sverginare",
        "svodit posrat",
        "svoloch",
        "swastika",
        "swinger",
        "sádico",
        "tainted love",
        "tanche",
        "tapette",
        "tarzanello",
        "taste my",
        "tea bagging",
        "terrone",
        "testa di cazzo",
        "tetas grandes",
        "tette",
        "teuch",
        "threesome",
        "throating",
        "thumbzilla",
        "tied up",
        "tight white",
        "tirare",
        "tit",
        "tits",
        "tittchen",
        "titten",
        "titties",
        "titty",
        "tongue in a",
        "topa",
        "topless",
        "torneira",
        "tosser",
        "towelhead",
        "trakhat'sya",
        "tranny",
        "transar",
        "travesti",
        "tribadism",
        "trimandoblydskiy pizdoproyob",
        "tringler",
        "trio",
        "trique",
        "troia",
        "trombare",
        "troncher",
        "trou du cul",
        "tub girl",
        "tubgirl",
        "turlute",
        "tushy",
        "twat",
        "twink",
        "twinkie",
        "two girls one cup",
        "tía buena",
        "u'ebitsche",
        "ubl'yudok",
        "uboy",
        "undressing",
        "upskirt",
        "urethra play",
        "urophilia",
        "v pizdu",
        "vacca",
        "vadia",
        "vaffanculo",
        "vafl'a",
        "vafli lovit",
        "vagina",
        "vai tomar no cu",
        "vai-te foder",
        "vangare",
        "veado",
        "venus mound",
        "verga",
        "vete a la mierda",
        "viagra",
        "vibrador",
        "vibrator",
        "violet wand",
        "vollpfosten",
        "vorarephilia",
        "voyeur",
        "voyeurweb",
        "voyuer",
        "vulva",
        "vyperdysh",
        "vzdrochennyi",
        "vögeln",
        "wank",
        "wet dream",
        "wetback",
        "white power",
        "whore",
        "wichse",
        "wichsen",
        "wichser",
        "worldsex",
        "wrapping men",
        "wrinkled starfish",
        "xana",
        "xochota",
        "xxx",
        "yaoi",
        "yeb vas",
        "yellow showers",
        "yiffy",
        "za'ebat",
        "zaebis",
        "zalupa",
        "zalupat",
        "zasranetc",
        "zassat",
        "zigounette",
        "zinne",
        "zio cantante",
        "zizi",
        "zlo'ebuchy",
        "zoccola",
        "zoophilia",
        "ânus",
        "étron",
        "бздёнок",
        "блядки",
        "блядовать",
        "блядство",
        "блядь",
        "бугор",
        "во пизду",
        "встать раком",
        "выёбываться",
        "гандон",
        "говно",
        "говнюк",
        "голый",
        "дать пизды",
        "дерьмо",
        "дрочить",
        "другой дразнится",
        "ебать",
        "ебать-копать",
        "ебло",
        "ебнуть",
        "жопа",
        "жополиз",
        "играть на кожаной флейте",
        "измудохать",
        "каждый дрочит как он хочет",
        "как два пальца обоссать",
        "какая разница",
        "курите мою трубку",
        "лысого в кулаке гонять",
        "малофья",
        "манда",
        "мандавошка",
        "мент",
        "муда",
        "мудило",
        "мудозвон",
        "на фиг",
        "на хуй",
        "на хую вертеть",
        "на хуя",
        "наебать",
        "наебениться",
        "наебнуться",
        "нахуячиться",
        "не ебет",
        "невебенный",
        "ни за хуй собачу",
        "ни хуя",
        "обнаженный",
        "обоссаться можно",
        "один ебётся",
        "опесдол",
        "офигеть",
        "охуеть",
        "охуительно",
        "половое сношение",
        "секс",
        "сиськи",
        "спиздить",
        "срать",
        "ссать",
        "траxать",
        "ты мне ваньку не валяй",
        "фига",
        "хапать",
        "хер с ней",
        "хер с ним",
        "хохол",
        "хрен",
        "хуем груши околачивать",
        "хуеплет",
        "хуило",
        "хуиней страдать",
        "хуиня",
        "хуй",
        "хуй пинать",
        "хуйнуть",
        "хуёво",
        "хуёвый",
        "ёб твою мать",
        "ёбарь",
        "אורגזמה",
        "אירוטי",
        "אירוטיקה",
        "בובת מין",
        "דילדו",
        "ויברטור",
        "זונה",
        "זונות",
        "זיון",
        "חשפנית",
        "לחדירה",
        "מין אנאלי",
        "מציצה",
        "סקס",
        "עירום",
        "פורנו",
        "פורנוגרפיה",
        "צעצועי מין",
        "احتلام",
        "اغتصاب",
        "بزاز",
        "بظر",
        "بيضان",
        "تمص",
        "ثدي",
        "جماع",
        "حلمة",
        "خنثي",
        "خول",
        "سحاق",
        "سحاقية",
        "سكس",
        "شاذ",
        "شرج",
        "شرموطة",
        "شهوة",
        "طيز",
        "عاهرة",
        "عرص",
        "فرج",
        "قحبة",
        "قضيب",
        "لبوة",
        "لحس",
        "لعق",
        "لواط",
        "لوطي",
        "مبادل",
        "متناك",
        "متناكة",
        "مفلقسة",
        "نيك",
    ],
    'allow' => [
        "analog",
        "analogue",
        "analysis",
        "analytics",
        "assembly",
        "assessment",
        "assistant",
        "banana",
        "bikini",
        "breast milk",
        "breast pump",
        "breastfeeding",
        "canal",
        "classic",
        "cockpit",
        "cockroach",
        "cocktail",
        "compass",
        "essex",
        "foot massage",
        "glasses",
        "grape",
        "grapefruit",
        "lingerie set",
        "massage chair",
        "massage gun",
        "maternity",
        "middlesex",
        "neck massage",
        "nursing bra",
        "peacock",
        "scrape",
        "scraper",
        "sexton",
        "shuttlecock",
        "sussex",
        "swimwear",
        "therapist",
        "therapy",
        "underwear",
    ],
];
